[build]
  command = "gatsby build"
  publish = "public"

[build.environment]
  YARN_VERSION = "3.3.1"
  YARN_FLAGS = "--no-ignore-optional"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"
	[plugins.inputs]
	sitemapPath = "/sitemap-index.xml"
	ignorePeriod = 0